(function(global){
"use strict";
var config=global.AxialTimesheetConfig;
var context=global.AxialQB.context.create({application:"timesheet",version:config.version,environment:"development",mode:"self",allowedModes:["self","resource"]});
var state={config:config,context:context,periods:[],currentPeriod:null,currentIndex:0,tasks:[],entries:{},resources:[]};
function periods(){var future=config.weekRange.future,past=config.weekRange.past;for(var i=-future;i<=past;i++){var d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-7*i);d.setDate(d.getDate()-d.getDay());var end=new Date(d);end.setDate(end.getDate()+6);state.periods.push({start:new Date(d),end:end});}state.currentIndex=future;state.currentPeriod=state.periods[future];}
function optionLabel(p){return p.start.toDateString()+" - "+p.end.toDateString();}
function initWeeks(){periods();var sel=global.jQuery("#weekSelector").empty();state.periods.forEach(function(p,i){sel.append("<option value='"+i+"'>"+optionLabel(p)+"</option>");});sel.val(String(state.currentIndex)).off("change.ts").on("change.ts",function(){changeWeek(parseInt(this.value,10));});}
function setBusy(message){global.jQuery("#loadingState").text(message||"").toggle(!!message);}
function chooseResource(){if(context.mode==="self"){context.selectedResourceId=context.loggedInUserId;context.selectedResourceName=context.loggedInUserName||"My Timesheet";global.jQuery("#statusResourceName").text(context.selectedResourceName);return Promise.resolve();}return global.AxialTimesheetData.loadResources(state).then(function(rows){var requested=context.requestedResourceId,selected=rows.filter(function(r){return String(r.id)===String(requested);})[0];if(selected){context.selectedResourceId=selected.id;context.selectedResourceName=selected.name;}renderResourceSelector();});}
function renderResourceSelector(){global.jQuery("#resourceNav").show();var sel=global.jQuery("#resourceSelector").empty().append("<option value=''>Select Employee</option>");state.resources.forEach(function(r){sel.append("<option value='"+r.id+"'>"+r.name+"</option>");});sel.val(context.selectedResourceId||"").off("change.ts").on("change.ts",function(){var id=this.value;if(!id){return;}if(global.AxialTimesheetView.countDirty(state)&&!global.confirm("You have unsaved changes. Change employee anyway?")){this.value=context.selectedResourceId||"";return;}var r=state.resources.filter(function(x){return String(x.id)===String(id);})[0];if(!r){return;}context.selectedResourceId=r.id;context.selectedResourceName=r.name;reloadData();});}
function reloadData(){if(!context.selectedResourceId){global.jQuery("#timesheet-container").html("<div class='empty-state'>Select an employee to load the timesheet.</div>");return Promise.resolve();}setBusy("Loading timesheet...");return global.AxialTimesheetData.loadTasks(state).then(function(){return global.AxialTimesheetData.loadEntries(state);}).then(function(){context.taskCount=state.tasks.length;context.entryCount=Object.keys(state.entries).reduce(function(n,k){return n+state.entries[k].length;},0);global.AxialTimesheetView.render(state);setBusy("");updateDiagnostics();}).catch(function(error){setBusy("");global.AxialQB.logger.error("timesheet.load.failed",error.message,error.details||{});global.jQuery("#timesheet-container").html("<div class='error-state'>Timesheet failed to load. "+error.message+" Correlation ID: "+context.correlationId+"</div>");updateDiagnostics();});}
function changeWeek(index){if(global.AxialTimesheetView.countDirty(state)&&!global.confirm("You have unsaved changes. Change week anyway?")){global.jQuery("#weekSelector").val(String(state.currentIndex));return;}state.currentIndex=index;state.currentPeriod=state.periods[index];context.weekIndex=index;context.weekStart=state.currentPeriod.start.toISOString();context.weekEnd=state.currentPeriod.end.toISOString();global.AxialTimesheetView.render(state);updateDiagnostics();}
function shiftWeek(delta){var next=Math.max(0,Math.min(state.periods.length-1,state.currentIndex+delta));if(next!==state.currentIndex){global.jQuery("#weekSelector").val(String(next)).trigger("change");}}
function save(){if(!global.AxialTimesheetView.countDirty(state)){return;}global.jQuery("#saveButton").prop("disabled",true).text("Saving...");global.AxialTimesheetData.save(state).then(function(saved){if(saved){return reloadData();}}).then(function(){global.jQuery("#saveButton").text("Save");}).catch(function(error){global.AxialQB.logger.error("timesheet.save.failed",error.message,error.details||{});global.alert("Unable to save the timesheet. Correlation ID: "+context.correlationId);global.AxialTimesheetView.refresh(state);global.jQuery("#saveButton").text("Save");});}
function loggerRecords(){var logger=global.AxialQB&&global.AxialQB.logger;if(!logger){return [];}if(typeof logger.getRecords==="function"){return logger.getRecords();}if(typeof logger.getEntries==="function"){return logger.getEntries();}return [];}
function updateDiagnostics(){context.selectedResourceId=context.selectedResourceId||null;context.weekIndex=state.currentIndex;context.weekStart=state.currentPeriod&&state.currentPeriod.start.toISOString();context.weekEnd=state.currentPeriod&&state.currentPeriod.end.toISOString();context.dirtyEntries=global.AxialTimesheetView.countDirty(state);var records=loggerRecords();global.jQuery("#diagnosticsContent").text(JSON.stringify({context:context,errors:records.slice(-25)},null,2));global.jQuery("#diagnosticsButton").toggle(context.debug||records.length>0);}
function applicationDbid(){var parts=(global.location.pathname||"").split("/").filter(function(x){return !!x;});var dbIndex=parts.indexOf("db");if(dbIndex>=0&&parts[dbIndex+1]){return parts[dbIndex+1];}return "";}
function validateAliases(aliases){var required=[config.tableAliases.tasks,config.tableAliases.timeEntries];if(context.mode==="resource"){required.push(config.tableAliases.resources);}var missing=required.filter(function(name){return !aliases[name];});if(missing.length){throw new Error("Quickbase table aliases could not be resolved: "+missing.join(", "));}}
function start(){global.AxialQB.logger.configure({contextProvider:function(){return context;}});global.AxialQB.logger.installGlobalHandlers();initWeeks();global.jQuery("#prevWeekBtn").on("click",function(){shiftWeek(1);});global.jQuery("#nextWeekBtn").on("click",function(){shiftWeek(-1);});global.jQuery("#todayBtn").on("click",function(){global.jQuery("#weekSelector").val(String(config.weekRange.future)).trigger("change");});global.jQuery("#saveButton").on("click",save);global.jQuery("#diagnosticsButton").on("click",function(){updateDiagnostics();global.jQuery("#diagnosticsPanel").toggle();});setBusy("Loading Quickbase context...");Promise.all([global.AxialQB.quickbase.getCurrentUserProfile(config.appToken),global.AxialQB.quickbase.getAppTables(applicationDbid(),config.appToken)]).then(function(results){var profile=results[0];context.loggedInUserId=profile.id;context.loggedInUserName=profile.name;global.aliasMap=results[1]||{};validateAliases(global.aliasMap);return chooseResource();}).then(reloadData).catch(function(error){setBusy("");global.AxialQB.logger.error("timesheet.bootstrap.failed",error.message,error.details||{});global.jQuery("#timesheet-container").html("<div class='error-state'>Timesheet could not initialize. "+error.message+" Correlation ID: "+context.correlationId+"</div>");updateDiagnostics();});}
global.AxialTimesheet={state:state,start:start,save:save,reload:reloadData};
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",start);}else{start();}
}(window));