(function(global){
"use strict";
var $=global.jQuery,dayNames=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],collapsedGroups={};
function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function dayClass(d){var now=new Date();now.setHours(0,0,0,0);if(d.getTime()===now.getTime()){return" today-col";}return(d.getDay()===0||d.getDay()===6)?" weekend-col":"";}
function visible(task,period,config){var s=task.startDate,e=task.endDate,l=task.lastEntryDate;if(config.overheadTypes.indexOf(task.projectType)>=0){return task.status==="In Process"&&(!s||s<=period.end)&&(!e||e>=period.start);}var active=(!s||s<=period.end)&&(task.status==="In Process"||!e||e>=period.start)&&(task.remainingHours>0||task.allowOverbudget);return active||!!(l&&l>=period.start&&l<=period.end);}
function entryFor(state,taskId,date){var list=state.entries[taskId]||[],time=date.getTime(),found=null;list.some(function(e){if(e.date&&e.date.getTime()===time){found=e;return true;}return false;});return found;}
function ensureEntry(state,taskId,date){var found=entryFor(state,taskId,date);if(found){return found;}found={id:"new-"+taskId+"-"+date.getTime(),taskId:taskId,standardHours:"",standardNote:"",overtimeHours:"",internalComment:"",date:new Date(date),approved:false,payrollApproved:false,dirty:false};state.entries[taskId]=state.entries[taskId]||[];state.entries[taskId].push(found);return found;}
function colgroup(){var h="<colgroup><col class='ts-col-code'><col class='ts-col-task'>";for(var i=0;i<7;i++){h+="<col class='ts-col-day'>";}return h+="<col class='ts-col-budget'><col class='ts-col-total'></colgroup>";}
function ensureShell(){var main=$(".ts-main"),footer=$("#timesheet-daily-totals");if(!$("#timesheet-week-header").length){$("<div id='timesheet-week-header' class='ts-week-header'></div>").insertBefore("#timesheet-container");}if(!footer.length){$("body").append("<div id='timesheet-daily-totals' class='ts-daily-totals'></div>");footer=$("#timesheet-daily-totals");}main.css("bottom","78px");footer.css({position:"fixed",left:"12px",right:"12px",bottom:"0",zIndex:110,minWidth:0,overflow:"hidden"});main.off("scroll.tsRails").on("scroll.tsRails",syncFixedFooter);$(global).off("resize.tsRails").on("resize.tsRails",syncFixedFooter);}
function syncFixedFooter(){var main=$(".ts-main")[0],footer=$("#timesheet-daily-totals"),table=footer.find("table");if(!main||!table.length){return;}var width=Math.max(1114,main.clientWidth-24);table.css({width:width+"px",minWidth:width+"px",transform:"translateX("+(-main.scrollLeft)+"px)"});}
function render(state){ensureShell();var root=$("#timesheet-container").empty(),groups={};$("#timesheet-week-header").html(weekHeader(state));$("#timesheet-daily-totals").html(totals(state));state.tasks.forEach(function(t){if(visible(t,state.currentPeriod,state.config)){(groups[t.projectType]=groups[t.projectType]||[]).push(t);}});Object.keys(groups).forEach(function(type){root.append(card(state,type,groups[type]));});bind(state);refresh(state);syncFixedFooter();}
function weekHeader(state){var h="<table aria-label='Timesheet week columns'>"+colgroup()+"<thead><tr><th class='ts-col-code'>Code</th><th class='ts-col-task'>Project / Task</th>";for(var i=0;i<7;i++){var d=new Date(state.currentPeriod.start);d.setDate(d.getDate()+i);h+="<th class='day-col ts-col-day"+dayClass(d)+"' data-day='"+i+"'><small>"+dayNames[d.getDay()]+"</small><b>"+d.getDate()+"</b></th>";}return h+="<th class='ts-col-budget'>Remaining</th><th class='ts-col-total'>Total</th></tr></thead></table>";}
function card(state,type,tasks){var key=String(type),collapsed=!!collapsedGroups[key],h="<section class='project-card"+(collapsed?" is-collapsed":"")+"' data-group='"+esc(key)+"'><button type='button' class='project-card__header' aria-expanded='"+(!collapsed)+"'><span class='project-card__title'><span class='project-card__chevron' aria-hidden='true'>"+(collapsed?"&#9656;":"&#9662;")+"</span><strong>"+esc(type)+"</strong></span><span class='project-card__count'>"+tasks.length+" task"+(tasks.length===1?"":"s")+"</span></button><div class='project-card__body'"+(collapsed?" style='display:none'":"")+"><div class='table-responsive'><table class='timesheet-grid'>"+colgroup()+"<tbody>";tasks.forEach(function(t){h+=row(state,t);});return h+="</tbody></table></div></div></section>";}
function noteButton(state,e,kind,date){var isExternal=kind==="standardNote",hasText=!!(isExternal?e.standardNote:e.internalComment),images=state.config.images||{},src=isExternal?(hasText?images.standardNoteFilled:images.standardNoteEmpty):(hasText?images.internalNoteFilled:images.internalNoteEmpty),title=isExternal?(hasText?"Edit external note":"Add external note"):(hasText?"Edit internal comment":"Add internal comment");return "<button type='button' class='note-btn"+(hasText?" has-note":"")+"' data-kind='"+kind+"' data-date='"+date.getTime()+"' title='"+title+"' aria-label='"+title+"'><img src='"+esc(src||"")+"' alt=''></button>";}
function row(state,task){var h="<tr class='task-row' data-task-id='"+esc(task.id)+"'><td class='ts-col-code'><b class='project-code'>"+esc(task.projectCode)+"</b></td><td class='ts-col-task'><div class='task-name'>"+esc(task.taskName)+"</div><div class='project-description'>"+esc(task.projectDescription)+"</div></td>";for(var i=0;i<7;i++){var d=new Date(state.currentPeriod.start);d.setDate(d.getDate()+i);var e=entryFor(state,task.id,d)||{},locked=e.approved||e.payrollApproved,otDisabled=locked||!task.allowOvertime;h+="<td class='entry-cell ts-col-day"+dayClass(d)+"'><div class='entry-line'><input class='hours standard-hours' data-kind='standard' data-day='"+i+"' data-date='"+d.getTime()+"' value='"+esc(e.standardHours||"")+"' "+(locked?"disabled":"")+">"+noteButton(state,e,"standardNote",d)+"</div><div class='entry-line overtime-line'><input class='hours overtime-hours' data-kind='overtime' data-day='"+i+"' data-date='"+d.getTime()+"' value='"+esc(e.overtimeHours||"")+"' "+(otDisabled?"disabled":"")+">"+noteButton(state,e,"internalComment",d)+"</div></td>";}return h+="<td class='budget-cell ts-col-budget'>"+fmt(task.remainingHours)+"</td><td class='task-total ts-col-total'>0</td></tr>";}
function totals(state){var h="<table aria-label='Daily timesheet totals'>"+colgroup()+"<tbody><tr><th colspan='2'>Regular Hours</th>";for(var i=0;i<7;i++){var rd=new Date(state.currentPeriod.start);rd.setDate(rd.getDate()+i);h+="<td class='regular-total"+dayClass(rd)+"' data-day='"+i+"'>0</td>";}h+="<td></td><td id='regularWeekTotal' class='week-total'>0</td></tr><tr><th colspan='2'>Overtime Hours</th>";for(var j=0;j<7;j++){var od=new Date(state.currentPeriod.start);od.setDate(od.getDate()+j);h+="<td class='overtime-total"+dayClass(od)+"' data-day='"+j+"'>0</td>";}return h+="<td></td><td id='overtimeWeekTotal' class='week-total'>0</td></tr></tbody></table>";}
function bind(state){$(".hours").off("change.ts keydown.ts focus.ts").on("focus.ts",function(){this.select();}).on("change.ts",function(){changeHours(state,$(this));}).on("keydown.ts",function(ev){keyboard($(this),ev);});$(".note-btn").off("click.ts").on("click.ts",function(){openNote(state,$(this));});$(".project-card__header").off("click.tsCollapse").on("click.tsCollapse",function(){toggleCard($(this));});$("#timesheetSearch").off("input.ts").on("input.ts",filter);}
function toggleCard(header){var card=header.closest(".project-card"),body=card.find(".project-card__body").first(),key=String(card.data("group")||""),collapsed=!card.hasClass("is-collapsed");card.toggleClass("is-collapsed",collapsed);body.toggle(!collapsed);header.attr("aria-expanded",String(!collapsed));header.find(".project-card__chevron").html(collapsed?"&#9656;":"&#9662;");collapsedGroups[key]=collapsed;}
function changeHours(state,input){var raw=input.val(),value=raw===""?"":parseFloat(raw);if(raw!==""&&(isNaN(value)||value<0)){alert("Hours must be a non-negative number.");render(state);return;}if(value!==""){value=Math.ceil(value/state.config.hourIncrement)*state.config.hourIncrement;input.val(value);}var row=input.closest("tr"),taskId=String(row.data("taskId")),task=state.tasks.filter(function(t){return String(t.id)===taskId;})[0],date=new Date(parseInt(input.data("date"),10)),entry=ensureEntry(state,taskId,date),prop=input.data("kind")==="standard"?"standardHours":"overtimeHours",old=parseFloat(entry[prop])||0,next=parseFloat(value)||0,delta=next-old;if(!task.allowOverbudget&&delta>task.remainingHours){alert("The entry exceeds the remaining task budget.");render(state);return;}entry[prop]=value;entry.dirty=true;task.remainingHours-=delta;input.addClass("unsaved");state.context.dirtyEntries=countDirty(state);refresh(state);}
function openNote(state,button){var taskId=String(button.closest("tr").data("taskId")),date=new Date(parseInt(button.data("date"),10)),entry=ensureEntry(state,taskId,date),kind=button.data("kind"),title=kind==="standardNote"?"Timesheet Note (External)":"Internal Comment";$("#noteTitle").text(title);$("#note").val(entry[kind]||"");$("#noteModalSaveButton").off("click.ts").on("click.ts",function(){entry[kind]=$("#note").val();entry.dirty=true;state.context.dirtyEntries=countDirty(state);render(state);});$("#noteModal").modal("show");}
function keyboard(input,ev){var key=ev.which||ev.keyCode;if([13,37,38,39,40].indexOf(key)<0){return;}ev.preventDefault();if(key===13){input.trigger("change");key=ev.shiftKey?37:39;}var row=input.closest("tr"),day=parseInt(input.data("day"),10),kind=input.data("kind"),targetRow=row,targetDay=day;if(key===37){targetDay=Math.max(0,day-1);}if(key===39){targetDay=Math.min(6,day+1);}if(key===38){targetRow=row.prevAll(".task-row:visible").first();}if(key===40){targetRow=row.nextAll(".task-row:visible").first();}var target=targetRow.find(".hours[data-kind='"+kind+"'][data-day='"+targetDay+"']:not(:disabled)");if(target.length){target.focus();}}
function refresh(state){var reg=[0,0,0,0,0,0,0],ot=[0,0,0,0,0,0,0];$(".task-row").each(function(){var total=0;$(this).find(".hours").each(function(){var v=parseFloat($(this).val())||0,day=parseInt($(this).data("day"),10);total+=v;if($(this).data("kind")==="standard"){reg[day]+=v;}else{ot[day]+=v;}});$(this).find(".task-total").text(fmt(total));var id=String($(this).data("taskId")),task=state.tasks.filter(function(t){return String(t.id)===id;})[0];$(this).find(".budget-cell").text(fmt(task.remainingHours));});var rw=0,ow=0;for(var i=0;i<7;i++){rw+=reg[i];ow+=ot[i];$(".regular-total[data-day='"+i+"']").text(fmt(reg[i]));$(".overtime-total[data-day='"+i+"']").text(fmt(ot[i]));$(".day-col[data-day='"+i+"']").toggleClass("over-limit",reg[i]>state.config.maxDailyHours);}$("#regularWeekTotal,#statusWeekTotal").text(fmt(rw));$("#overtimeWeekTotal,#statusOvertimeTotal").text(fmt(ow));$("#saveButton").prop("disabled",countDirty(state)===0).toggleClass("dirty",countDirty(state)>0);$("#statusResourceName").text(state.context.selectedResourceName||"");syncFixedFooter();}
function filter(){var q=String($(this).val()||"").toLowerCase();$(".project-card").each(function(){var card=$(this),rows=card.find(".task-row"),matches=0;rows.each(function(){var hit=!q||$(this).text().toLowerCase().indexOf(q)>=0;$(this).toggle(hit);if(hit){matches++;}});card.toggle(matches>0);if(q&&matches>0){card.find(".project-card__body").show();}else if(!q){card.find(".project-card__body").toggle(!card.hasClass("is-collapsed"));}});}
function countDirty(state){var n=0;Object.keys(state.entries).forEach(function(k){state.entries[k].forEach(function(e){if(e.dirty){n++;}});});return n;}
function fmt(v){v=parseFloat(v)||0;return Math.abs(v-Math.round(v))<0.0001?String(Math.round(v)):v.toFixed(2).replace(/0+$/,'').replace(/\.$/,'');}
global.AxialTimesheetView={render:render,refresh:refresh,countDirty:countDirty};
}(window));